
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b3d800af-9772-4626-8f65-27807bab1bf1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.7" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot/files/**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="App_Data\" />
  </ItemGroup>
</Project>
